name: Test building image

on:
  schedule:
    - cron: '0 0,15-23/3 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  building_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: |
        ./build-docker.sh onedocker

