name: Build and Publish Binary Image
run-name: Build ${{ inputs.image_to_build }} Image on ${{ inputs.tag }} branch

on:
  workflow_call:
    inputs:
      image_to_build:
        description: Which image we should build. Can be either emp_games or data_processing
        required: true
        type: string
      tag:
        description: The docker tag to publish with
        required: true
        default: latest
        type: string
      fbpcf_version:
        description: The FBPCF version to build with
        required: true
        default: latest
        type: string
      load_image_locally:
        description: A boolean on whether we should load the image locally or not.
        required: false
        default: false
        type: boolean
      push_to_registry:
        description: A boolean on whether we should push the image to the RC registry or not.
        required: false
        default: false
        type: boolean

env:
  DISTRO: ubuntu
  REGISTRY: ghcr.io
  RC_REGISTRY_IMAGE_URL: ghcr.io/${{ github.repository }}/rc/

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ inputs.image_to_build }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ inputs.image_to_build }}

      - name: Pull FBPCF Image
        run: docker pull ghcr.io/facebookresearch/fbpcf/ubuntu:${{ inputs.fbpcf_version }}

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/${{ inputs.image_to_build }}/Dockerfile.ubuntu
          tags: |
            ${{ env.RC_REGISTRY_IMAGE_URL }}${{ inputs.image_to_build }}:${{ github.sha }}
            ${{ env.RC_REGISTRY_IMAGE_URL }}${{ inputs.image_to_build }}:${{ inputs.tag }}
          build-args: |
            tag=latest
            os_release=20.04
            fbpcf_image=ghcr.io/facebookresearch/fbpcf/ubuntu:${{ inputs.fbpcf_version }}
          push: ${{ inputs.push_to_registry }}
          load: ${{ inputs.load_image_locally }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # This ugly bit is necessary or else our cache will grow forever
      # until it hits GitHub's limit of 5GB.
      # Temp fix: T135482742
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
